# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost:7143

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Venu",
  "lastName": "vv",
  "email": "venu.vutukuru@gmail.com",
  "password":"venu1234%"
}